//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePlayList
    {
        public int Id { get; set; }
        public int IdMusica { get; set; }
        public int IdPlayList { get; set; }
    
        public virtual Musica Musica { get; set; }
        public virtual PlayList PlayList { get; set; }
    }
}
